name: C++ Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Conan
      uses: jwidauer/setup-conan@v1

    - name: Create Build Directory
      run: mkdir build

    - name: Configure CMake
      run: cmake -B build -S .
      shell: bash

    - name: Build
      run: cmake --build build
      shell: bash

    - name: Test
      run: ctest --test-dir build
      shell: bash
